

export const AGREGANDO_PRODUCTO = 'AGREGANDO_PRODUCTO';
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO';
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR';


export const OBTENIENDO_PRODUCTOS = 'OBTENIENDO_PRODUCTOS';
export const MOSTRAR_PRODUCTOS_EXITO = 'MOSTRAR_PRODUCTOS_EXITO';
export const MOSTRAR_PRODUCTOS_ERROR = 'MOSTRAR_PRODUCTOS_ERROR';

export const OBTENER_PRODUCTO_ELIMINAR = 'OBTENER_PRODUCTO_ELIMINAR';
export const PRODUCTO_ELIMINADO_EXITO = 'PRODUCTO_ELIMINADO_EXITO';
export const PRODUCTO_ELIMINADO_ERROR = 'PRODUCTO_ELIMINADO_ERROR';

export const OBTENER_PRODUCTO_EDITAR = 'OBTENER_PRODUCTO_EDITAR';
export const COMENZAR_EDICION = 'COMENZAR_EDICION';
export const PRODUCTO_EDITADO_EXITO = 'PRODUCTO_EDITADO_EXITO';
export const PRODUCTO_EDITADO_ERROR = 'PRODUCTO_ELIMINADO_ERROR';